// R9 F2: the unconditional "lib" entry in analyze.ts SKIP_DIRS analyzed every
// Dart/Flutter project (all source in lib/ by mandatory convention) and Ruby
// gem to ZERO files with no log — and generate-once froze the empty
// DEVLOG_STACK.md forever, surviving any later fix. The sibling scanner.ts
// skip list never had "lib" (same two-list drift class as #605), so language
// detection worked while the deep analysis was dead. Fix: skip lib/ only under
// a JS/TS root (package.json), and let generateStackMd regenerate over a file
// that records an empty analysis.

import { describe, test, expect } from "bun:test";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { analyzeProject } from "../src/analyze";
import { generateStackMd, stackFileIsGenerated } from "../src/export";
import type { ProjectProfile } from "../src/types";

const DART_MAIN = "void main() { print(greet()); }\nString greet() { return 'hi'; }\n";

function mkProfile(dir: string, over: Partial<ProjectProfile> = {}): ProjectProfile {
  return {
    name: "lib-fixture", path: dir, description: "", blueprint: [],
    language: "Dart", framework: "", libraries: [], files: {},
    directories: [], totalFiles: 1, lastScan: "2026-01-01T00:00:00Z", ...over,
  };
}

describe("lib/ skip is ecosystem-conditional (R9 F2)", () => {
  test("Dart project: lib/ IS analyzed (no package.json root)", async () => {
    const dir = mkdtempSync(join(tmpdir(), "devlog-dart-"));
    try {
      writeFileSync(join(dir, "pubspec.yaml"), "name: fixture\n");
      mkdirSync(join(dir, "lib", "src"), { recursive: true });
      writeFileSync(join(dir, "lib", "main.dart"), DART_MAIN);
      writeFileSync(join(dir, "lib", "src", "util.dart"), "int add(int a, int b) { return a + b; }\n");

      const analysis = await analyzeProject(dir);
      const paths = analysis.files.map(f => f.path);
      expect(paths).toContain("lib/main.dart");
      expect(paths).toContain("lib/src/util.dart");
      expect(analysis.totalLines).toBeGreaterThan(0);
    } finally { rmSync(dir, { recursive: true, force: true }); }
  });

  test("JS package: root lib/ stays skipped when package.json points main at it", async () => {
    const dir = mkdtempSync(join(tmpdir(), "devlog-jslib-"));
    try {
      writeFileSync(join(dir, "package.json"), JSON.stringify({ name: "x", version: "1.0.0", main: "lib/index.js" }));
      writeFileSync(join(dir, "index.ts"), "export function real() { return 1; }\n");
      mkdirSync(join(dir, "lib"));
      writeFileSync(join(dir, "lib", "index.js"), "module.exports.compiled = function compiled() { return 1; };\n");

      const analysis = await analyzeProject(dir);
      const paths = analysis.files.map(f => f.path);
      expect(paths).toContain("index.ts");
      expect(paths).not.toContain("lib/index.js");
    } finally { rmSync(dir, { recursive: true, force: true }); }
  });
});

describe("generateStackMd heals the frozen empty residue (R9 F2)", () => {
  test("a stack file recording 0 lines / 0 functions is regenerated", async () => {
    const dir = mkdtempSync(join(tmpdir(), "devlog-residue-"));
    try {
      writeFileSync(join(dir, "pubspec.yaml"), "name: fixture\n");
      mkdirSync(join(dir, "lib"));
      writeFileSync(join(dir, "lib", "main.dart"), DART_MAIN);
      // The exact residue the old skip left behind for a Flutter project.
      mkdirSync(join(dir, ".devlog"));
      writeFileSync(join(dir, ".devlog", "DEVLOG_STACK.md"),
        "# lib-fixture\n\n## Stack\n- **الملفات**: 1 ملف | 0 سطر | 0 دالة\n");

      await generateStackMd(dir, mkProfile(dir));
      const md = readFileSync(join(dir, ".devlog", "DEVLOG_STACK.md"), "utf8");
      expect(md).not.toMatch(/\| 0 سطر \| 0 دالة/);
      expect(md).toContain("main.dart");
    } finally { rmSync(dir, { recursive: true, force: true }); }
  });

  // #1093: the generated file carries a body-hash trailer. An automatic
  // regeneration overwrites a file whose body still matches its trailer (nobody
  // edited it) and a legacy file without a trailer (frozen at first hook); a
  // file whose body DIFFERS from its trailer is a manual edit and survives.
  test("a generated stack file is regenerated by the automatic path (no more generate-once)", async () => {
    const dir = mkdtempSync(join(tmpdir(), "devlog-regen-"));
    try {
      writeFileSync(join(dir, "pubspec.yaml"), "name: fixture\n");
      mkdirSync(join(dir, "lib"));
      writeFileSync(join(dir, "lib", "main.dart"), DART_MAIN);
      await generateStackMd(dir, mkProfile(dir));
      const first = readFileSync(join(dir, ".devlog", "DEVLOG_STACK.md"), "utf8");
      expect(first).toMatch(/<!-- devlog:stack [0-9a-f]+ -->\s*$/);
      expect(stackFileIsGenerated(first)).toBe(true);
      // the project grows → the next automatic generation reflects it
      writeFileSync(join(dir, "lib", "extra.dart"), "int twice(int a) { return a * 2; }\n");
      await generateStackMd(dir, mkProfile(dir, { totalFiles: 2 }));
      const second = readFileSync(join(dir, ".devlog", "DEVLOG_STACK.md"), "utf8");
      expect(second).toContain("extra.dart");
    } finally { rmSync(dir, { recursive: true, force: true }); }
  });

  test("a manually edited stack file (body ≠ trailer) survives the automatic path", async () => {
    const dir = mkdtempSync(join(tmpdir(), "devlog-keep-"));
    try {
      writeFileSync(join(dir, "pubspec.yaml"), "name: fixture\n");
      mkdirSync(join(dir, "lib"));
      writeFileSync(join(dir, "lib", "main.dart"), DART_MAIN);
      await generateStackMd(dir, mkProfile(dir));
      const generated = readFileSync(join(dir, ".devlog", "DEVLOG_STACK.md"), "utf8");
      const manual = generated.replace("# lib-fixture", "# lib-fixture\n\nملاحظاتي اليدوية");
      expect(stackFileIsGenerated(manual)).toBe(false);
      writeFileSync(join(dir, ".devlog", "DEVLOG_STACK.md"), manual);
      const before = statSync(join(dir, ".devlog", "DEVLOG_STACK.md")).mtimeMs;

      await generateStackMd(dir, mkProfile(dir));
      const md = readFileSync(join(dir, ".devlog", "DEVLOG_STACK.md"), "utf8");
      expect(md).toBe(manual);
      expect(statSync(join(dir, ".devlog", "DEVLOG_STACK.md")).mtimeMs).toBe(before);
      // explicit regeneration (dashboard button) still overrides
      await generateStackMd(dir, mkProfile(dir), true);
      expect(readFileSync(join(dir, ".devlog", "DEVLOG_STACK.md"), "utf8")).not.toContain("ملاحظاتي اليدوية");
    } finally { rmSync(dir, { recursive: true, force: true }); }
  });
});
