// The rule under test: a file's WRITTEN purpose beats the guess. These cases
// are mostly about the ways extraction must REFUSE — a wrong description is
// worse than the heuristic fallback, so every ambiguous input must yield "".

import { test, expect, describe } from "bun:test";
import { filePurposeFromHeader, describeFile } from "../src/file-purpose";
import type { FileAnalysis } from "../src/analyze";

const fa = (over: Partial<FileAnalysis> = {}): FileAnalysis => ({
  path: "src/thing.ts", lines: 100, imports: [], exports: [], functions: [],
  patterns: [], routes: [], context: "server", description: "", ...over,
} as FileAnalysis);

describe("filePurposeFromHeader — the two header conventions", () => {
  test("header BEFORE the imports", () => {
    const src = [
      "// Keeps the hot event log bounded without losing history. More prose",
      "// that continues the same paragraph.",
      "",
      'import { x } from "./x";',
      "export const a = 1;",
    ].join("\n");
    expect(filePurposeFromHeader(src)).toBe("Keeps the hot event log bounded without losing history");
  });

  test("header AFTER the import block (this repo's older convention)", () => {
    const src = [
      'import { readdir } from "node:fs/promises";',
      'import type { DevLogData } from "./types";',
      "",
      "// Append-only forensic log for destructive operations. Second sentence.",
      "export function f() {}",
    ].join("\n");
    expect(filePurposeFromHeader(src)).toBe("Append-only forensic log for destructive operations");
  });

  test("multi-line import braces don't abort the scan", () => {
    const src = [
      "import {",
      "  openTodos,",
      "  openBugs,",
      '} from "./data";',
      "",
      "// Inverse of the open-item resolver: which items are NOW closed.",
      "export const x = 1;",
    ].join("\n");
    expect(filePurposeFromHeader(src)).toBe("Inverse of the open-item resolver: which items are NOW closed");
  });

  test("JSDoc block header", () => {
    const src = [
      "/**",
      " * Closure check — detect content that matches an open item. Details follow.",
      " */",
      "export function check() {}",
    ].join("\n");
    expect(filePurposeFromHeader(src)).toBe("Closure check — detect content that matches an open item");
  });

  test("shebang before the header", () => {
    const src = ["#!/usr/bin/env bun", "/**", " * devlog doctor — diagnose tracking gaps in a project.", " */"].join("\n");
    expect(filePurposeFromHeader(src)).toBe("devlog doctor — diagnose tracking gaps in a project");
  });

  test("python-style # header after imports", () => {
    const src = ["import os", "from x import y", "", "# Loads the model weights and warms the cache on boot."].join("\n");
    expect(filePurposeFromHeader(src)).toBe("Loads the model weights and warms the cache on boot");
  });
});

describe("filePurposeFromHeader — refusals (fall back to the heuristic)", () => {
  test("no comment at all", () => {
    expect(filePurposeFromHeader('import { a } from "./a";\nexport const b = 1;\n')).toBe("");
  });

  test("code before the comment → the comment documents that code, not the file", () => {
    const src = ["export const A = 1;", "", "// Explains the helper below, not the file.", "function helper() {}"].join("\n");
    expect(filePurposeFromHeader(src)).toBe("");
  });

  test("licence / copyright boilerplate is refused", () => {
    for (const first of ["// Copyright (c) 2020 Someone. All rights reserved.", "// SPDX-License-Identifier: MIT", "/* Licensed under the Apache License, Version 2.0 */"]) {
      expect(filePurposeFromHeader(`${first}\nexport const a = 1;`)).toBe("");
    }
  });

  test("tooling directives are refused", () => {
    for (const first of ["// eslint-disable-next-line no-console", "// @ts-nocheck", "// biome-ignore lint: whatever", "// Auto-generated by protoc. DO NOT EDIT."]) {
      expect(filePurposeFromHeader(`${first}\nexport const a = 1;`)).toBe("");
    }
  });

  test("a section-rule banner is not a purpose", () => {
    expect(filePurposeFromHeader("// ─── Helpers ───────────\nexport const a = 1;")).toBe("");
  });

  test("a too-short stub is noise", () => {
    expect(filePurposeFromHeader("// TODO\nexport const a = 1;")).toBe("");
  });

  test("empty / missing content", () => {
    expect(filePurposeFromHeader("")).toBe("");
    expect(filePurposeFromHeader(undefined as unknown as string)).toBe("");
  });
});

describe("filePurposeFromHeader — output is table-cell safe", () => {
  test("pipes are neutralized so a markdown row can't be split", () => {
    const out = filePurposeFromHeader("// Renders a | b | c into the report table for the client.\nexport const a = 1;");
    expect(out).not.toContain("|");
    expect(out.length).toBeGreaterThan(12);
  });

  test("single line, collapsed whitespace", () => {
    const out = filePurposeFromHeader("// Does\t a   thing\n//   across  lines and keeps going for a while here.\nexport const a = 1;");
    expect(out).not.toContain("\n");
    expect(out).not.toContain("  ");
  });

  test("long headers are cut on a word boundary with an ellipsis", () => {
    const long = `// ${"word ".repeat(60)}`;
    const out = filePurposeFromHeader(`${long}\nexport const a = 1;`);
    expect(out.length).toBeLessThanOrEqual(111);
    expect(out.endsWith("…")).toBe(true);
    expect(out).toMatch(/word…$/);           // cut landed on a word boundary, not mid-word
  });

  test("dots inside versions/filenames don't cut the sentence early", () => {
    const out = filePurposeFromHeader("// DEVLOG_HTML_SPEC v1.0 implementation for data.ts consumers everywhere.\nexport const a = 1;");
    expect(out).toBe("DEVLOG_HTML_SPEC v1.0 implementation for data.ts consumers everywhere");
  });

  test("a title line ending without punctuation stops before the next sentence", () => {
    const src = [
      "// Cold event archive: pruning archives, never deletes",
      "// The hot store keeps only the recent events per project.",
      "export const a = 1;",
    ].join("\n");
    expect(filePurposeFromHeader(src)).toBe("Cold event archive: pruning archives, never deletes");
  });

  test("a WRAPPED line is not mistaken for a title (ends on a connector)", () => {
    const src = [
      "// Reads the project configuration from disk and merges it with",
      "// Windows-specific overrides before anyone sees it.",
      "export const a = 1;",
    ].join("\n");
    expect(filePurposeFromHeader(src))
      .toBe("Reads the project configuration from disk and merges it with Windows-specific overrides before anyone sees it");
  });

  test("an ALL-CAPS final word is emphasis, not the end of a title", () => {
    const src = [
      "// Inverse of the open-item resolver (data.ts): which numbered items are NOW",
      "// CLOSED, and when they were closed.",
      "export const a = 1;",
    ].join("\n");
    expect(filePurposeFromHeader(src))
      .toBe("Inverse of the open-item resolver (data.ts): which numbered items are NOW CLOSED, and when they were closed");
  });

  test("an unclosed bracket means the thought continues", () => {
    const src = [
      "// Shared Cargo.toml helpers used by BOTH the dependency scanner (scanner.ts",
      "// Plus the release path) and nothing else.",
      "export const a = 1;",
    ].join("\n");
    expect(filePurposeFromHeader(src)).toContain("Plus the release path)");
  });

  test("box-drawing rules are stripped even in short runs", () => {
    const src = ["// ── Test-context data guard (#736)", "// The preload rewrites the data dir for tests.", "export const a = 1;"].join("\n");
    expect(filePurposeFromHeader(src)).toBe("Test-context data guard (#736)");
  });

  test("only the FIRST paragraph is used", () => {
    const src = ["// First paragraph explaining the file's job here.", "//", "// Second paragraph with unrelated detail.", "export const a = 1;"].join("\n");
    expect(filePurposeFromHeader(src)).toBe("First paragraph explaining the file's job here");
  });
});

describe("describeFile — the fallback still works unchanged", () => {
  test("filename hint wins for known names", () => {
    expect(describeFile(fa({ path: "src/server.ts" }))).toBe("الراوتر الرئيسي");
  });

  test("hint gains endpoint/function counts", () => {
    const d = describeFile(fa({ path: "src/server.ts", routes: ["GET /a"], functions: [{}] as never }));
    expect(d).toContain("endpoint");
  });

  test("client context falls back to a UI label", () => {
    expect(describeFile(fa({ path: "assets/panel.js", context: "client" }))).toBe("واجهة مستخدم");
  });

  test("last resort is the export list, then a dash", () => {
    expect(describeFile(fa({ path: "src/zzz.ts", exports: ["a", "b"] }))).toBe("a, b");
    expect(describeFile(fa({ path: "src/zzz.ts" }))).toBe("—");
  });
});
