// Audit round 10, wave 3 — file-purpose, project-map, scanner docFiles.

import { describe, test, expect } from "bun:test";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { filePurposeFromHeader } from "../src/file-purpose";
import { buildMap } from "../src/project-map";
import { scanProject } from "../src/scanner";
import type { ProjectAnalysis } from "../src/analyze";

describe("filePurposeFromHeader — Rust inner docs (#1119)", () => {
  test("`//!` markers are stripped and a blank `//!` ends the paragraph", () => {
    const src = "//! Unified firewall binary for the desktop.\n//!\n//! Subcommands:\n//! - (no args) open the GUI\nuse std::env;\nfn main() {}\n";
    expect(filePurposeFromHeader(src)).toBe("Unified firewall binary for the desktop");
  });
  test("`/*! … */` inner block docs behave the same", () => {
    expect(filePurposeFromHeader("/*! Crate-level entry that wires the modules together. */\npub mod a;\n")).toBe("Crate-level entry that wires the modules together");
  });
});

describe("filePurposeFromHeader — `#` directives are not prose (#1120)", () => {
  test("C header guards and pragmas are skipped; the real header comment is read", () => {
    const src = "#ifndef COMMON_H\n#define COMMON_H\n#pragma once\n// Shared constants and helpers for the audio pipeline.\n#include <cstdint>\nstruct X {};\n#endif\n";
    expect(filePurposeFromHeader(src)).toBe("Shared constants and helpers for the audio pipeline");
  });
  test("a guarded header with no comment yields nothing, not «ifndef COMMON_H define COMMON_H»", () => {
    expect(filePurposeFromHeader("#ifndef COMMON_H\n#define COMMON_H\nint f();\n#endif\n")).toBe("");
    expect(filePurposeFromHeader('#pragma comment(lib, "avrt.lib")\nvoid g();\n')).toBe("");
  });
  test("Rust attributes are not purposes; the doc line after them is", () => {
    expect(filePurposeFromHeader("#![allow(dead_code)]\n#[derive(Debug, Clone, Serialize)]\nstruct S;\n")).toBe("");
    expect(filePurposeFromHeader("#![allow(dead_code)]\n//! Indicator math shared by the chart widgets.\nuse x;\n")).toBe("Indicator math shared by the chart widgets");
  });
  test("Go build tags and generator stamps are not purposes", () => {
    expect(filePurposeFromHeader("//go:build devpg\n\npackage main\n")).toBe("");
    expect(filePurposeFromHeader("// Code generated by protoc-gen-go. DO NOT EDIT.\n// versions:\npackage pb\n")).toBe("");
    expect(filePurposeFromHeader("//go:build linux\n\n// Serves the dev page over a local socket for hot reload.\npackage main\n")).toBe("Serves the dev page over a local socket for hot reload");
  });
  test("Python coding cookie and linter pragmas are not purposes", () => {
    expect(filePurposeFromHeader("# -*- coding: utf-8 -*-\n# pylint: disable=missing-docstring\nimport os\n")).toBe("");
    expect(filePurposeFromHeader("# ruff: noqa: E501\nimport os\n")).toBe("");
    expect(filePurposeFromHeader("#!/usr/bin/env python\n# Probes the Huawei switch over SSH and prints the fault table.\nimport paramiko\n")).toBe("Probes the Huawei switch over SSH and prints the fault table");
  });
});

describe("buildMap — short queries are still queries (#1114)", () => {
  const analysis = {
    files: [
      { path: "assets/dashboard-tree-ws.js", lines: 10, imports: [], exports: [], functions: [], patterns: [], routes: [], context: "client", description: "WebSocket tree" },
      { path: "src/data.ts", lines: 10, imports: [], exports: [], functions: [], patterns: [], routes: [], context: "server", description: "store" },
      { path: "src/tags.ts", lines: 10, imports: [], exports: [], functions: [], patterns: [], routes: [], context: "server", description: "tags" },
    ],
    fileRanks: { "assets/dashboard-tree-ws.js": 0.2, "src/data.ts": 0.9, "src/tags.ts": 0.5 },
  } as unknown as ProjectAnalysis;

  test("`ws` filters to the file that carries it and reports the query", () => {
    const m = buildMap(analysis, "ws");
    expect(m.query).toBe("ws");
    expect(m.fellBack).toBeUndefined();
    expect(m.entries.map(e => e.path)).toEqual(["assets/dashboard-tree-ws.js"]);
  });
  test("a short query that matches nothing falls back VISIBLY", () => {
    const m = buildMap(analysis, "db");
    expect(m.query).toBe("db");
    expect(m.fellBack).toBe(true);
  });
  test("a one-letter query cannot filter and says so", () => {
    const m = buildMap(analysis, "c");
    expect(m.query).toBe("c");
    expect(m.fellBack).toBe(true);
    expect(m.entries.length).toBe(3);
  });
  test("no query is still the plain top-N", () => {
    const m = buildMap(analysis, "");
    expect(m.query).toBeUndefined();
    expect(m.fellBack).toBeUndefined();
  });
});

describe("scanProject docFiles reads DevLog's own docs (#1089)", () => {
  test("body-only docs described by index.json land in the profile", async () => {
    const dir = mkdtempSync(join(tmpdir(), "devlog-docs-"));
    try {
      writeFileSync(join(dir, "package.json"), JSON.stringify({ name: "x", version: "1.0.0" }));
      writeFileSync(join(dir, "index.ts"), "export const a = 1;\n");
      mkdirSync(join(dir, ".devlog", "docs"), { recursive: true });
      writeFileSync(join(dir, ".devlog", "docs", "index.json"), JSON.stringify([
        { slug: "plan-q3", name: "Plan Q3", type: "plan", createdAt: "2026-01-01T00:00:00Z", updatedAt: "2026-01-02T00:00:00Z" },
        { slug: "ghost", name: "Ghost", type: "report", createdAt: "2026-01-01T00:00:00Z", updatedAt: "2026-01-01T00:00:00Z" },
      ]));
      writeFileSync(join(dir, ".devlog", "docs", "plan-q3.md"), "# Plan Q3\n\n- [ ] step one\n");
      const profile = await scanProject(dir, p => p.split(/[\\/]/).pop() || "x");
      expect(profile.docFiles?.map(d => d.file)).toEqual(["plan-q3.md"]);
      expect(profile.docFiles?.[0]).toMatchObject({ name: "Plan Q3", type: "plan" });
      expect(profile.docFiles?.[0].body).toContain("step one");
    } finally { rmSync(dir, { recursive: true, force: true }); }
  });
});
