// How a file gets its one-line description in the stack map (DEVLOG_STACK.md,
// the dashboard's file tree). Two sources, in order:
//
//   1. What the file SAYS about itself — the purpose header its author wrote at
//      the top. This is the only source that knows *why* the file exists, and
//      it cannot drift, because it lives inside the file being described.
//   2. Heuristics — filename hints, detected patterns, exported names. A guess,
//      used only when the file documents nothing.
//
// The order is the whole point (#791 class): the old map had source 2 ONLY, so
// it stated things no one had claimed. A written purpose now always wins.
//
// The header is recognized in BOTH conventions this repo uses — before the
// imports, or directly after the import block — because the second is the older
// and more common one here. Scanning stops at the first real declaration, so a
// comment attached to some function further down is never mistaken for the
// file's purpose.
//
// Output is a table cell in generated markdown and a text node in the
// dashboard, so it is normalized here at the source: single line, pipes
// neutralized, capped length. Callers must not have to sanitize it again.

import type { FileAnalysis } from "./analyze";

/** Longest description we put in a table cell; longer headers are cut on a word
 *  boundary. Sized to keep the generated markdown table readable. */
const MAX_PURPOSE_CHARS = 110;

// Lines allowed to appear BEFORE the header without ending the search: shebang,
// pragmas, and the import block in every language the analyzer handles (JS/TS
// import|export-from|require, Python from|import, Rust use, Go package|import,
// C/C++ #include, PHP namespace|use).
const PRE_HEADER_LINE =
  /^\s*(#!|["']use strict["']|["']use client["']|import\b|export\s+(type\s+)?\{[^}]*\}\s*from\b|export\s+\*\s+from\b|from\s+\S+\s+import\b|const\s+\{?[\w\s,}]*\}?\s*=\s*require\(|use\s+[\w:{]|package\s+\w|#include\b|namespace\s+\w|@?using\s)/;

// A leading comment block that is NOT a purpose statement: tooling directives,
// legal boilerplate, generator stamps. Treating these as the file's purpose is
// worse than falling back to the heuristic.
const NOT_A_PURPOSE =
  /^(copyright|\(c\)|spdx|licen[cs]ed?\b|all rights reserved|eslint|prettier|biome-ignore|@ts-|jshint|globals?\s|istanbul|auto[- ]generated|generated by|do not edit|@flow|tslint)/i;

/** Strip one line's comment markers. Returns null when the line isn't a comment
 *  (so the caller can tell "end of block" from "empty comment line"). */
function commentText(line: string): string | null {
  const t = line.trim();
  if (t.startsWith("//")) return t.replace(/^\/\/+/, "").trim();
  if (t.startsWith("/**")) return t.replace(/^\/\*+/, "").replace(/\*+\/$/, "").trim();
  if (t.startsWith("/*")) return t.replace(/^\/\*+/, "").replace(/\*+\/$/, "").trim();
  if (t.startsWith("*/")) return "";
  if (t.startsWith("*")) return t.replace(/^\*+/, "").replace(/\*+\/$/, "").trim();
  if (t.startsWith("#") && !t.startsWith("#!") && !t.startsWith("#include")) return t.replace(/^#+/, "").trim();
  return null;
}

/** True while the line may precede the header (blank, pragma, import, or a
 *  continuation line of a multi-line import/use block). */
function isPreHeader(line: string, inBlock: boolean): { ok: boolean; inBlock: boolean } {
  const t = line.trim();
  if (!t) return { ok: true, inBlock };
  if (inBlock) return { ok: true, inBlock: !/[)};]\s*$/.test(t) };
  if (!PRE_HEADER_LINE.test(t)) return { ok: false, inBlock: false };
  // A multi-line import (`import {\n a,\n b,\n} from "x"`) keeps going until its
  // closing brace/paren — otherwise its member lines read as "real code" and
  // abort the scan before the header that follows.
  const opens = /[{(]\s*$/.test(t) || (/[{(]/.test(t) && !/[)}]\s*(from\b|;|$)/.test(t));
  return { ok: true, inBlock: opens };
}

// Words that can only be mid-sentence: a line ending in one of these is a
// WRAPPED line, never a finished thought.
const CONNECTORS = new Set([
  "with", "and", "or", "the", "a", "an", "of", "to", "in", "for", "from", "that",
  "which", "into", "by", "on", "at", "as", "is", "are", "was", "were", "per",
  "its", "their", "this", "these", "those", "than", "then", "so", "but", "not",
  "no", "it", "we", "they", "he", "she", "you", "when", "while", "if", "over",
  "under", "between", "about", "after", "before", "each", "every", "any", "all",
]);

/**
 * True when the paragraph's current last line is a TITLE line — a complete
 * thought written without terminal punctuation, followed by a new sentence.
 * Headers in this repo often open that way (`// Cold event archive: pruning
 * archives, never deletes` then `// The hot store keeps …`); without this the
 * two run together into one unreadable cell.
 *
 * Conservative on purpose — it only fires when the line does NOT end mid-phrase
 * and the next line starts a capitalized Latin word. Anything else keeps
 * joining, which is the old, safe behavior.
 */
function endsTitleLine(para: string[], nextText: string | null): boolean {
  const line = para[para.length - 1];
  const joined = para.join(" ");
  if (joined.length < 25) return false;            // too little to stand alone
  if (/[.!?؟:,;—–\-→/+&]$/.test(line)) return false;  // ends mid-phrase
  // An opener still waiting for its closer means the thought continues, however
  // the line happens to end (`… (scanner.ts →` + `OSV scan)`).
  for (const [open, close] of [["(", ")"], ["[", "]"], ["«", "»"], ["`", "`"]] as const) {
    const opens = joined.split(open).length - 1;
    const closes = open === close ? opens : joined.split(close).length - 1;
    if (open === close ? opens % 2 === 1 : opens > closes) return false;
  }
  const lastWord = (line.match(/[\w'’]+$/) || [""])[0];
  if (CONNECTORS.has(lastWord.toLowerCase())) return false;
  // An ALL-CAPS final word is emphasis inside a sentence (`… items are NOW` +
  // `CLOSED, and …`), not the end of a title.
  if (lastWord.length > 1 && lastWord === lastWord.toUpperCase() && /[A-Z]/.test(lastWord)) return false;
  return !!nextText && /^[A-Z]/.test(nextText);
}

/**
 * The first sentence of a file's purpose header, or "" when it has none.
 *
 * Deliberately conservative — every rule below exists so a WRONG description
 * can't be produced (an empty result just falls back to the heuristic):
 * scanning stops at the first declaration, tooling/licence blocks are refused,
 * and only the first paragraph of the block is considered.
 */
export function filePurposeFromHeader(content: string): string {
  const lines = (content || "").split("\n", 200);
  let i = 0;
  let inBlock = false;

  // Walk past shebang / pragmas / imports to the first comment line.
  for (; i < lines.length; i++) {
    if (commentText(lines[i]) !== null) break;
    const state = isPreHeader(lines[i], inBlock);
    if (!state.ok) return "";   // real code before any comment → no file header
    inBlock = state.inBlock;
  }
  if (i >= lines.length) return "";

  // Collect the first paragraph of the block (an empty comment line ends it).
  const para: string[] = [];
  for (; i < lines.length; i++) {
    const text = commentText(lines[i]);
    if (text === null) break;          // block ended
    if (!text) { if (para.length) break; continue; }  // blank line inside/leading
    if (!para.length && NOT_A_PURPOSE.test(text)) return "";
    // Banner rules (`// ─── Title ───`, `// ===== Title =====`) are decoration:
    // drop the runs per line — BEFORE the title-line test, which measures real
    // text — and keep whatever title they framed. `─` is box-drawing, never
    // prose, so even a short run of it goes; a plain `-` needs three.
    const cleaned = text.replace(/─+/g, " ").replace(/[=*_]{3,}|-{3,}/g, " ").replace(/\s+/g, " ").trim();
    if (!cleaned) { if (para.length) break; continue; }   // a pure rule line reads as blank
    para.push(cleaned);
    if (endsTitleLine(para, commentText(lines[i + 1] ?? ""))) break;
  }
  if (!para.length) return "";

  let s = para.join(" ").replace(/\s+/g, " ").trim();
  if (!s) return "";

  // First sentence only. `.` is required to be followed by a space so version
  // numbers and file names (`v1.0`, `data.ts`) don't cut the line in half.
  const stop = s.search(/[.!?؟](\s|$)/);
  if (stop > 20) s = s.slice(0, stop);

  // Markdown table cell: pipes would open a new column, newlines break the row.
  s = s.replace(/\|/g, "/").replace(/\s+/g, " ").trim();

  if (s.length > MAX_PURPOSE_CHARS) {
    const cut = s.lastIndexOf(" ", MAX_PURPOSE_CHARS);
    s = `${s.slice(0, cut > 40 ? cut : MAX_PURPOSE_CHARS).trim()}…`;
  }
  return s.length >= 12 ? s : "";   // a 3-word stub is noise, not a purpose
}

// ─── Heuristic fallback (used only when the file documents nothing) ──────────

/**
 * Guess a description from the filename, detected patterns and exports. Moved
 * here from analyze.ts with the header extractor it now backs up: both answer
 * the same question, and keeping them together is what makes the "written
 * purpose wins" rule visible in one place.
 */
export function describeFile(fa: FileAnalysis): string {
  const fullName = fa.path.split("/").pop() || "";
  const ext = fullName.split(".").pop()?.toLowerCase() || "";
  const name = fullName.replace(/\.\w+$/, "");

  // Non-code files
  if (ext === "css") return `أنماط CSS${fa.lines > 500 ? ` (${fa.lines} سطر)` : ""}`;
  if (ext === "html" || ext === "htm") return `صفحة HTML${fa.lines > 100 ? " (تطبيق)" : ""}`;
  const nameHints: Record<string, string> = {
    server: "الراوتر الرئيسي", router: "الراوتر", data: "إدارة البيانات (تحميل/حفظ)",
    broadcast: "بث WebSocket للعملاء", scanner: "مسح المشروع وكشف اللغة والمكتبات",
    hooks: "تحليل أحداث Claude Code hooks", export: "تصدير التقارير (status, changelog, stack)",
    tree: "بناء شجرة الملفات مع .devignore", plans: "تحليل خطط Markdown",
    types: "تعريف الأنواع (interfaces)", analyze: "تحليل عميق للكود (imports, exports, routes)",
    index: "نقطة الدخول", main: "نقطة الدخول", app: "التطبيق الرئيسي",
    config: "الإعدادات", utils: "دوال مساعدة", helpers: "دوال مساعدة",
    middleware: "middleware", auth: "المصادقة والصلاحيات",
    db: "اتصال قاعدة البيانات", database: "اتصال قاعدة البيانات",
    model: "نماذج البيانات", models: "نماذج البيانات", schema: "مخطط البيانات",
    test: "اختبارات", spec: "اختبارات",
    widgets: "نظام الودجتات", widget: "ودجت",
    style: "الأنماط (CSS)", styles: "الأنماط (CSS)",
    theme: "نظام الثيمات", themes: "نظام الثيمات",
    layout: "التخطيط والتوزيع",
    state: "إدارة الحالة", store: "إدارة الحالة",
    api: "طبقة الاتصال بالـ API", service: "طبقة الخدمات",
    worker: "عملية خلفية (Worker)", logger: "نظام التسجيل",
    cache: "نظام التخزين المؤقت", queue: "نظام الطوابير",
    usage: "معلومات الاستخدام", cli: "واجهة سطر الأوامر",
  };
  const hint = nameHints[name.toLowerCase()];
  if (hint) {
    const extras: string[] = [];
    if (fa.routes.length > 0) extras.push(`${fa.routes.length} endpoint`);
    if (fa.functions.length > 0) extras.push(`${fa.functions.length} دالة`);
    return extras.length > 0 ? `${hint} (${extras.join(", ")})` : hint;
  }
  // Context-aware fallback
  const parts: string[] = [];
  if (fa.context === "client") parts.push("واجهة مستخدم");
  if (fa.routes.length > 0) parts.push(`${fa.routes.length} endpoint`);
  if (fa.context !== "client" && fa.patterns.includes("HTTP Server")) parts.push("سيرفر");
  if (fa.patterns.includes("WebSocket")) parts.push("WebSocket");
  if (fa.patterns.includes("Database")) parts.push("قاعدة بيانات");
  if (fa.patterns.includes("Auth")) parts.push("مصادقة");
  if (fa.patterns.includes("DOM") && !parts.includes("واجهة مستخدم")) parts.push("واجهة مستخدم");
  if (parts.length > 0) return parts.join(" + ");
  if (fa.exports.length > 0) return fa.exports.slice(0, 3).join(", ");
  return "—";
}
