// How a file gets its one-line description in the stack map (DEVLOG_STACK.md,
// the dashboard's file tree). Two sources, in order:
//
//   1. What the file SAYS about itself — the purpose header its author wrote at
//      the top. This is the only source that knows *why* the file exists, and
//      it cannot drift, because it lives inside the file being described.
//   2. Heuristics — filename hints, detected patterns, exported names. A guess,
//      used only when the file documents nothing.
//
// The order is the whole point (#791 class): the old map had source 2 ONLY, so
// it stated things no one had claimed. A written purpose now always wins.
//
// The header is recognized in BOTH conventions this repo uses — before the
// imports, or directly after the import block — because the second is the older
// and more common one here. Scanning stops at the first real declaration, so a
// comment attached to some function further down is never mistaken for the
// file's purpose.
//
// Output is a table cell in generated markdown and a text node in the
// dashboard, so it is normalized here at the source: single line, pipes
// neutralized, capped length. Callers must not have to sanitize it again.

import type { FileAnalysis } from "./analyze";
import { currentLang } from "./i18n";

/** Longest description we put in a table cell; longer headers are cut on a word
 *  boundary. Sized to keep the generated markdown table readable. */
const MAX_PURPOSE_CHARS = 110;

// Lines allowed to appear BEFORE the header without ending the search: shebang,
// pragmas, and the import block in every language the analyzer handles (JS/TS
// import|export-from|require, Python from|import, Rust use, Go package|import,
// C/C++ #include, PHP namespace|use).
const PRE_HEADER_LINE =
  /^\s*(#!|["']use strict["']|["']use client["']|import\b|export\s+(type\s+)?\{[^}]*\}\s*from\b|export\s+\*\s+from\b|from\s+\S+\s+import\b|const\s+\{?[\w\s,}]*\}?\s*=\s*require\(|use\s+[\w:{]|package\s+\w|#include\b|namespace\s+\w|@?using\s|#\s*(?:if|ifdef|ifndef|define|endif|else|elif|undef|pragma|import|error|warning)\b|#!?\[|\/\/\s*(?:go:|nolint\b|\+build))/;

// A leading comment block that is NOT a purpose statement: tooling directives,
// legal boilerplate, generator stamps. Treating these as the file's purpose is
// worse than falling back to the heuristic. Includes the Python coding cookie
// and linter pragmas (`# -*- coding`, `# pylint:`, `# ruff:`, `# noqa`,
// `# type:`, `# mypy:`) and the Go generator stamp mid-line ("Code generated
// by protoc-gen-go. DO NOT EDIT.") — all of which read as purposes before (#1120).
const NOT_A_PURPOSE =
  /^(copyright|\(c\)|spdx|licen[cs]ed?\b|all rights reserved|eslint|prettier|biome-ignore|@ts-|jshint|globals?\s|istanbul|auto[- ]generated|(code\s+)?generated by|do not edit|@flow|tslint|-\*-|coding[:=]|pylint|ruff:|noqa|type:\s|mypy|flake8|isort)/i;

// Lines that start with `#` but are DIRECTIVES, never prose: C preprocessor
// (`#ifndef COMMON_H`, `#pragma comment(lib, …)`), Rust attributes
// (`#[derive(…)]`, `#![allow(…)]`), shebangs. They used to be read as comment
// text and printed as the file's purpose — «ifndef COMMON_H define COMMON_H»
// for every guarded C header (#1120).
const HASH_DIRECTIVE = /^#(?:!|\s*(?:include|import|if|ifdef|ifndef|define|endif|else|elif|undef|pragma|error|warning|line)\b|!?\[)/;
// `//` lines that are compiler directives, not comments (Go build tags, lint pragmas).
const SLASH_DIRECTIVE = /^\/\/\s*(?:go:|nolint\b|\+build\b)/;

/** Strip one line's comment markers. Returns null when the line isn't a comment
 *  (so the caller can tell "end of block" from "empty comment line"). */
function commentText(line: string): string | null {
  const t = line.trim();
  if (SLASH_DIRECTIVE.test(t)) return null;
  // `//!` (Rust inner doc) and `///` (outer doc) are doc comments: the `!` is
  // part of the marker, not the text. Kept, it printed as «! Unified firewall
  // binary. ! !» and a blank `//!` never ended the paragraph (#1119).
  if (t.startsWith("//")) return t.replace(/^\/\/+!?/, "").trim();
  if (t.startsWith("/**")) return t.replace(/^\/\*+!?/, "").replace(/\*+\/$/, "").trim();
  if (t.startsWith("/*")) return t.replace(/^\/\*+!?/, "").replace(/\*+\/$/, "").trim();
  if (t.startsWith("*/")) return "";
  if (t.startsWith("*")) return t.replace(/^\*+/, "").replace(/\*+\/$/, "").trim();
  if (t.startsWith("#") && !HASH_DIRECTIVE.test(t)) return t.replace(/^#+/, "").trim();
  return null;
}

/** True while the line may precede the header (blank, pragma, import, or a
 *  continuation line of a multi-line import/use block). */
function isPreHeader(line: string, inBlock: boolean): { ok: boolean; inBlock: boolean } {
  const t = line.trim();
  if (!t) return { ok: true, inBlock };
  if (inBlock) return { ok: true, inBlock: !/[)};]\s*$/.test(t) };
  if (!PRE_HEADER_LINE.test(t)) return { ok: false, inBlock: false };
  // A multi-line import (`import {\n a,\n b,\n} from "x"`) keeps going until its
  // closing brace/paren — otherwise its member lines read as "real code" and
  // abort the scan before the header that follows.
  const opens = /[{(]\s*$/.test(t) || (/[{(]/.test(t) && !/[)}]\s*(from\b|;|$)/.test(t));
  return { ok: true, inBlock: opens };
}

// Words that can only be mid-sentence: a line ending in one of these is a
// WRAPPED line, never a finished thought.
const CONNECTORS = new Set([
  "with", "and", "or", "the", "a", "an", "of", "to", "in", "for", "from", "that",
  "which", "into", "by", "on", "at", "as", "is", "are", "was", "were", "per",
  "its", "their", "this", "these", "those", "than", "then", "so", "but", "not",
  "no", "it", "we", "they", "he", "she", "you", "when", "while", "if", "over",
  "under", "between", "about", "after", "before", "each", "every", "any", "all",
]);

/**
 * True when the paragraph's current last line is a TITLE line — a complete
 * thought written without terminal punctuation, followed by a new sentence.
 * Headers in this repo often open that way (`// Cold event archive: pruning
 * archives, never deletes` then `// The hot store keeps …`); without this the
 * two run together into one unreadable cell.
 *
 * Conservative on purpose — it only fires when the line does NOT end mid-phrase
 * and the next line starts a capitalized Latin word. Anything else keeps
 * joining, which is the old, safe behavior.
 */
function endsTitleLine(para: string[], nextText: string | null): boolean {
  const line = para[para.length - 1];
  const joined = para.join(" ");
  if (joined.length < 25) return false;            // too little to stand alone
  if (/[.!?؟:,;—–\-→/+&]$/.test(line)) return false;  // ends mid-phrase
  // An opener still waiting for its closer means the thought continues, however
  // the line happens to end (`… (scanner.ts →` + `OSV scan)`).
  for (const [open, close] of [["(", ")"], ["[", "]"], ["«", "»"], ["`", "`"]] as const) {
    const opens = joined.split(open).length - 1;
    const closes = open === close ? opens : joined.split(close).length - 1;
    if (open === close ? opens % 2 === 1 : opens > closes) return false;
  }
  const lastWord = (line.match(/[\w'’]+$/) || [""])[0];
  if (CONNECTORS.has(lastWord.toLowerCase())) return false;
  // An ALL-CAPS final word is emphasis inside a sentence (`… items are NOW` +
  // `CLOSED, and …`), not the end of a title.
  if (lastWord.length > 1 && lastWord === lastWord.toUpperCase() && /[A-Z]/.test(lastWord)) return false;
  return !!nextText && /^[A-Z]/.test(nextText);
}

/**
 * The first sentence of a file's purpose header, or "" when it has none.
 *
 * Deliberately conservative — every rule below exists so a WRONG description
 * can't be produced (an empty result just falls back to the heuristic):
 * scanning stops at the first declaration, tooling/licence blocks are refused,
 * and only the first paragraph of the block is considered.
 */
export function filePurposeFromHeader(content: string): string {
  const lines = (content || "").split("\n", 200);
  let i = 0;
  let inBlock = false;

  // Walk past shebang / pragmas / imports to the first comment line.
  for (; i < lines.length; i++) {
    if (commentText(lines[i]) !== null) break;
    const state = isPreHeader(lines[i], inBlock);
    if (!state.ok) return "";   // real code before any comment → no file header
    inBlock = state.inBlock;
  }
  if (i >= lines.length) return "";

  // Collect the first paragraph of the block (an empty comment line ends it).
  const para: string[] = [];
  for (; i < lines.length; i++) {
    const text = commentText(lines[i]);
    if (text === null) break;          // block ended
    if (!text) { if (para.length) break; continue; }  // blank line inside/leading
    if (!para.length && NOT_A_PURPOSE.test(text)) return "";
    // Banner rules (`// ─── Title ───`, `// ===== Title =====`) are decoration:
    // drop the runs per line — BEFORE the title-line test, which measures real
    // text — and keep whatever title they framed. `─` is box-drawing, never
    // prose, so even a short run of it goes; a plain `-` needs three.
    const cleaned = text.replace(/─+/g, " ").replace(/[=*_]{3,}|-{3,}/g, " ").replace(/\s+/g, " ").trim();
    if (!cleaned) { if (para.length) break; continue; }   // a pure rule line reads as blank
    para.push(cleaned);
    if (endsTitleLine(para, commentText(lines[i + 1] ?? ""))) break;
  }
  if (!para.length) return "";

  let s = para.join(" ").replace(/\s+/g, " ").trim();
  if (!s) return "";

  // First sentence only. `.` is required to be followed by a space so version
  // numbers and file names (`v1.0`, `data.ts`) don't cut the line in half.
  const stop = s.search(/[.!?؟](\s|$)/);
  if (stop > 20) s = s.slice(0, stop);

  // Markdown table cell: pipes would open a new column, newlines break the row.
  s = s.replace(/\|/g, "/").replace(/\s+/g, " ").trim();

  if (s.length > MAX_PURPOSE_CHARS) {
    const cut = s.lastIndexOf(" ", MAX_PURPOSE_CHARS);
    s = `${s.slice(0, cut > 40 ? cut : MAX_PURPOSE_CHARS).trim()}…`;
  }
  return s.length >= 12 ? s : "";   // a 3-word stub is noise, not a purpose
}

// ─── Heuristic fallback (used only when the file documents nothing) ──────────

/**
 * Guess a description from the filename, detected patterns and exports. Moved
 * here from analyze.ts with the header extractor it now backs up: both answer
 * the same question, and keeping them together is what makes the "written
 * purpose wins" rule visible in one place.
 */
// Fallback descriptions follow DEVLOG_LANG like every other generated string
// (#1189): after the #906 sweep this was the last Arabic-only emitter, so an
// English-UI user saw Arabic file descriptions in the stack map / project map.
const L = (en: string, ar: string): string => (currentLang() === "ar" ? ar : en);

export function describeFile(fa: FileAnalysis): string {
  const fullName = fa.path.split("/").pop() || "";
  const ext = fullName.split(".").pop()?.toLowerCase() || "";
  const name = fullName.replace(/\.\w+$/, "");

  // Non-code files
  if (ext === "css") return `${L("CSS styles", "أنماط CSS")}${fa.lines > 500 ? ` (${fa.lines} ${L("lines", "سطر")})` : ""}`;
  if (ext === "html" || ext === "htm") return `${L("HTML page", "صفحة HTML")}${fa.lines > 100 ? ` (${L("app", "تطبيق")})` : ""}`;
  const nameHints: Record<string, [string, string]> = {
    server: ["main router", "الراوتر الرئيسي"], router: ["router", "الراوتر"], data: ["data management (load/save)", "إدارة البيانات (تحميل/حفظ)"],
    broadcast: ["WebSocket broadcast to clients", "بث WebSocket للعملاء"], scanner: ["project scan: language + library detection", "مسح المشروع وكشف اللغة والمكتبات"],
    hooks: ["Claude Code hook event parsing", "تحليل أحداث Claude Code hooks"], export: ["report export (status, changelog, stack)", "تصدير التقارير (status, changelog, stack)"],
    tree: ["file tree with .devignore", "بناء شجرة الملفات مع .devignore"], plans: ["Markdown plan parsing", "تحليل خطط Markdown"],
    types: ["type definitions (interfaces)", "تعريف الأنواع (interfaces)"], analyze: ["deep code analysis (imports, exports, routes)", "تحليل عميق للكود (imports, exports, routes)"],
    index: ["entry point", "نقطة الدخول"], main: ["entry point", "نقطة الدخول"], app: ["main application", "التطبيق الرئيسي"],
    config: ["configuration", "الإعدادات"], utils: ["helper functions", "دوال مساعدة"], helpers: ["helper functions", "دوال مساعدة"],
    middleware: ["middleware", "middleware"], auth: ["authentication & permissions", "المصادقة والصلاحيات"],
    db: ["database connection", "اتصال قاعدة البيانات"], database: ["database connection", "اتصال قاعدة البيانات"],
    model: ["data models", "نماذج البيانات"], models: ["data models", "نماذج البيانات"], schema: ["data schema", "مخطط البيانات"],
    test: ["tests", "اختبارات"], spec: ["tests", "اختبارات"],
    widgets: ["widget system", "نظام الودجتات"], widget: ["widget", "ودجت"],
    style: ["styles (CSS)", "الأنماط (CSS)"], styles: ["styles (CSS)", "الأنماط (CSS)"],
    theme: ["theming", "نظام الثيمات"], themes: ["theming", "نظام الثيمات"],
    layout: ["layout", "التخطيط والتوزيع"],
    state: ["state management", "إدارة الحالة"], store: ["state management", "إدارة الحالة"],
    api: ["API client layer", "طبقة الاتصال بالـ API"], service: ["service layer", "طبقة الخدمات"],
    worker: ["background worker", "عملية خلفية (Worker)"], logger: ["logging", "نظام التسجيل"],
    cache: ["caching", "نظام التخزين المؤقت"], queue: ["queueing", "نظام الطوابير"],
    usage: ["usage info", "معلومات الاستخدام"], cli: ["command-line interface", "واجهة سطر الأوامر"],
  };
  const hintPair = nameHints[name.toLowerCase()];
  if (hintPair) {
    const hint = L(hintPair[0], hintPair[1]);
    const extras: string[] = [];
    if (fa.routes.length > 0) extras.push(`${fa.routes.length} endpoint`);
    if (fa.functions.length > 0) extras.push(`${fa.functions.length} ${L("functions", "دالة")}`);
    return extras.length > 0 ? `${hint} (${extras.join(", ")})` : hint;
  }
  // Context-aware fallback
  const ui = L("user interface", "واجهة مستخدم");
  const parts: string[] = [];
  if (fa.context === "client") parts.push(ui);
  if (fa.routes.length > 0) parts.push(`${fa.routes.length} endpoint`);
  if (fa.context !== "client" && fa.patterns.includes("HTTP Server")) parts.push(L("server", "سيرفر"));
  if (fa.patterns.includes("WebSocket")) parts.push("WebSocket");
  if (fa.patterns.includes("Database")) parts.push(L("database", "قاعدة بيانات"));
  if (fa.patterns.includes("Auth")) parts.push(L("auth", "مصادقة"));
  if (fa.patterns.includes("DOM") && !parts.includes(ui)) parts.push(ui);
  if (parts.length > 0) return parts.join(" + ");
  if (fa.exports.length > 0) return fa.exports.slice(0, 3).join(", ");
  return "—";
}
